### ISSUE TITLE
JUnit tesztek

### ISSUE THREAD

**Issue by dzsef** [BME-MIT-IET/iet-hf-2024-tappancs-iet#5]
- [x] Tanulmányzzátok a kódot, és a várható kimeneteket
- [x] Készítsetek JUNIT teszteket a főbb funkciókhoz
- [x] Checkeljétek, hogy a CI konfigot hozzá

**Comment by Trogbolt** [comment]
3744b000d13ef9bfbdeba6e6c7fd631c28c1b773 ebben a commitban hozzáadtam a JUnit függőséget a projekthez.

**Comment by Trogbolt** [comment]
86a85183497e3fc3c8611031fafc74a95e7642c3 ebben a commitban megírtam a drain unit tesztjeit.

**Comment by Trogbolt** [comment]
7e628e532cb29d6234c5c25f726a728e550b9ff1 ebben a commitban megírtam a pipe-hoz tartozó teszteket.

**Comment by Trogbolt** [comment]
88660a3889deb8c140b7d3f13361eea0b1f11939 ebben a commitban megírtam a pump-hoz tartozó unit teszteket.

**Comment by Trogbolt** [comment]
c0842eff3f64346652d106fe2072695ce51c8d60 itt megcsináltam a hiányzó source teszteket, illetve javítottam a korábbi tesztek által talált hibát.

**Comment by Trogbolt** [comment]
7c68f804bc79d90c20ed028361aab97cea4837b0 az utolsó commitban kijavítottam, hogy csak a szabotőr tudjon szabotálni, illetve megírtam 2 hiányzó tesztet a pumpa átállítására.

**Comment by Trogbolt** [comment]
@ViolaAndo 47755dafbd7a8de257da31046dc8a967c27512c2 commitja után futtatunk lokálisan egy coverage tesztet Jacoco segítségével, ahol az alábbi eredményt kaptuk:
![first_coverage_test](https://github.com/BME-MIT-IET/iet-hf-2024-tappancs-iet/assets/94245397/5710708a-763b-47d7-80a9-ff241fd8ff13)

**Comment by Trogbolt** [comment]
Az utolsó 7c68f804bc79d90c20ed028361aab97cea4837b0 commit után újra futtattuk lokálisan a coverage tesztet és a következő eredményt kaptuk:
![second_coverage_test](https://github.com/BME-MIT-IET/iet-hf-2024-tappancs-iet/assets/94245397/1146cc9d-9ccf-4b1c-9b10-fe1fa5eb880a)

**Comment by ViolaAndo** [comment]
a76622e2e2d875dea40266e2c46e7b857f851950 Ebben a commitban megírtam a player unit tesztjeit.

**Comment by ViolaAndo** [comment]
8894c1685bdee0d45de2e60b77c31a0f56ce20a7 Ebben a commitban hozzáadtam a szabotőr unit tesztjeit.

**Comment by ViolaAndo** [comment]
47755dafbd7a8de257da31046dc8a967c27512c2 Ebben a commitban megcsináltam a szerelő unit tesztjeit.
